[postgresql]
DB_USER = "postgres"
DB_PASSWORD = "Gospel11"
DB_HOST = "postgres://umik8i508hes:p993b472f27470faf8a6faab8393a9b7ee3bbf431d5e4e3fb155d9d7c644fbf70@ce0lkuo944ch99.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d2ctpqma8a43i3"
DB_NAME = "sql_odyssey"
DB_PORT = "5432" 


ALTER USER postgres WITH PASSWORD 'Gospel11';
\q
