[postgresql]
DB_HOST = "ce0lkuo944ch99.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com"
DB_NAME = "d2ctpqma8a43i3"
DB_USER = "umik8i508hes"
DB_PASSWORD = "p993b472f27470faf8a6faab8393a9b7ee3bbf431d5e4e3fb155d9d7c644fbf70"
DB_PORT = "5432"

